CREATE TABLE PERSON (ID BIGINT NOT NULL, BIRTHDAY DATE, F_NAME VARCHAR(200) NOT NULL, GENDER VARCHAR(255), L_NAME VARCHAR(200) NOT NULL, SALARY DECIMAL(8,2), PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
