DROP TABLE RECIPE;
DROP TABLE INGREDIENT;
CREATE TABLE RECIPE (ID INT PRIMARY KEY, TITLE VARCHAR(255), PREAMBLE VARCHAR(500), ADDINGDATE DATE);
CREATE TABLE INGREDIENT (ID INT PRIMARY KEY, DESCRIPTION VARCHAR(255), RECIPE_ID INT);