insert into "COMPANY" ("ID", "NAME") values(10001, 'Intel')
insert into "COMPANY" ("ID", "NAME") values(10002, 'AMD')
insert into "COMPANY" ("ID", "NAME") values(10003, 'Microsoft')
insert into "COMPANY" ("ID", "NAME") values(10004, 'Google')
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2001, 'Brian', 'Krzanich', 10001)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2002, 'Lisa T.', 'Su', 10002)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2003, 'Mark', 'Papermaster', 10002)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2004, 'Bill', 'Gates', 10003)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2005, 'Nathan', 'Myhrvold', 10003)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2006, 'John W.', 'Thompson', 10003)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2007, 'Edward', 'Snowden', null)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2008, 'Julian', 'Assange', null)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2009, 'Larry', 'Page', 10004)
insert into "PERSON" ("ID", "FIRSTNAME", "LASTNAME", "COMPANY_ID") values(2010, 'Sergey', 'Brin', 10004)
insert into "ORDERING" ("ID", "ORDERNUMBER") values(5001, 1)
insert into "ORDERING" ("ID", "ORDERNUMBER") values(5002, 2)
insert into "ORDERING" ("ID", "ORDERNUMBER") values(5003, 3)
insert into "ORDERING" ("ID", "ORDERNUMBER") values(5004, 4)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6001, 'Gartenhandschuhe', 5001)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6002, 'Gartenschlauch', 5001)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6003, 'Rasenmäher', 5002)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6004, 'Rosenschere', 5002)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6005, 'Gieskanne', 5003)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6006, 'Gartenhandschuhe', 5003)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6007, 'Heckenschere', 5004)
insert into "ORDERITEM" ("ID", "DESCRIPTION", "ORDER_ID") values(6008, 'Wasserpumpe', 5004)

