CREATE TABLE EMPLOYEE (ID BIGINT NOT NULL, BIRTHDAY DATE, F_NAME VARCHAR(200) NOT NULL, GENDER VARCHAR(255), L_NAME VARCHAR(200) NOT NULL, SALARY DECIMAL(8,2), PRIMARY KEY (ID));
CREATE TABLE PROJECT (ID BIGINT NOT NULL, PROJECT_NAME VARCHAR(255) NOT NULL, PRIMARY KEY (ID));
CREATE TABLE EMP_PROJ (EMP_ID BIGINT NOT NULL, PROJ_ID BIGINT NOT NULL, PRIMARY KEY (EMP_ID, PROJ_ID));
ALTER TABLE EMP_PROJ ADD CONSTRAINT EMP_PROJ_PROJ_ID FOREIGN KEY (PROJ_ID) REFERENCES PROJECT (ID);
ALTER TABLE EMP_PROJ ADD CONSTRAINT FK_EMP_PROJ_EMP_ID FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE (ID);
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME));
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
