ALTER TABLE EMP_PROJ DROP CONSTRAINT EMP_PROJ_PROJ_ID;
ALTER TABLE EMP_PROJ DROP CONSTRAINT FK_EMP_PROJ_EMP_ID;
DROP TABLE EMPLOYEE;
DROP TABLE PROJECT;
DROP TABLE EMP_PROJ;
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
