ALTER TABLE INGREDIENT DROP FOREIGN KEY FK_INGREDIENT_RECIPE_ID;
ALTER TABLE TAGS DROP FOREIGN KEY FK_TAGS_RECIPE_ID;
DROP VIEW TAG_COUNT;
DROP TABLE RECIPE;
DROP TABLE INGREDIENT;
DROP TABLE TAGS;
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
DROP TABLE SEQUENCE;
